---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/Dicky_UTS
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp .hintrc $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
